name: Build report
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repo
        uses: actions/checkout@v2
      - name: Compile report
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report.tex
      - name: Upload PDF
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "report.pdf"
          target: "/var/www/html/nea/report.pdf"
