name: Build report
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repo
        uses: actions/checkout@v2
      - name: Compile report
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report.tex
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.pdf
